- name: Update packages
  apt:
    update_cache: true
    upgrade: "yes"

- name: Auto-remove old packages
  apt:
    autoremove: true

- name: Install additional packages (apt)
  package:
    name: "{{ additional_packages }}"
    use: apt
    state: present
  when: additional_packages is defined

- name: Disable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}" user
  lineinfile:
    path: /etc/sudoers
    regexp: "^%wheel%"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH daemon
  service:
    name: ssh
    state: restarted
  when: sshd_config.changed

- name: Set timezone
  lineinfile:
    path: /etc/timezone
    regexp: "^(.*)"
    line: "{{ timezone }}"
  when: timezone is defined

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists
